### ISSUE TITLE
undefined is not a function

### ISSUE THREAD

**Issue by RonnieStepOrange** [joeferraro/MavensMate-Atom#204]
Hi,

Since the upgrade to 0.0.22 I get the following error when loading a project.

Could not activate MavensMate project. MavensMate will not function correctly.
undefined is not a function.

Regards, Ronnie

**Comment by thvd** [comment]
Duplicate of: #203

**Comment by thvd** [comment]
You can run atom as `atom --include-deprecated-apis .`, than the error will disappear.

**Comment by RonnieStepOrange** [comment]
were do I put that?

**Comment by thvd** [comment]
You have to start Atom via the command line to use that solution.
